name: medi_supply_app_grupo3
description: "A new Flutter project."
publish_to: 'none' 

version: 0.1.0

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.35.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.2.4
  dio: ^5.9.0
  retrofit: ^4.7.3
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  equatable: ^2.0.7
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^3.2.3
  build_runner: ^2.9.0
  flutter_gen_runner: ^5.12.0 
  flutter_lints: ^6.0.0
  json_serializable: ^6.8.0
  retrofit_generator: ^10.0.6
  mockito: ^5.4.4

flutter_gen:
  output: lib/gen/

  integrations:
    image: true
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
