// Mocks generated by Mockito 5.4.6 from annotations
// in medi_supply_app_grupo3/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:medi_supply_app_grupo3/data/data_source/api/api_response.dart'
    as _i5;
import 'package:medi_supply_app_grupo3/data/data_source/dto/session/session_dto.dart'
    as _i6;
import 'package:medi_supply_app_grupo3/data/data_source/dto/user/user_credentials_dto.dart'
    as _i7;
import 'package:medi_supply_app_grupo3/data/data_source/remote/auth/auth_data_source_remote_interface.dart'
    as _i3;
import 'package:medi_supply_app_grupo3/data/repository/entity/session/session.dart'
    as _i2;
import 'package:medi_supply_app_grupo3/data/repository/entity/user/user_credentials.dart'
    as _i10;
import 'package:medi_supply_app_grupo3/data/repository/remote/auth/auth_repository_remote_interface.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSession_0 extends _i1.SmartFake implements _i2.Session {
  _FakeSession_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthDataSourceRemoteInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthDataSourceRemoteInterface extends _i1.Mock
    implements _i3.AuthDataSourceRemoteInterface {
  MockAuthDataSourceRemoteInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.ApiResponse<_i6.SessionDto>> login(
    _i7.UserCredentialsDto? userCredentials,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [userCredentials]),
            returnValue: _i4.Future<_i5.ApiResponse<_i6.SessionDto>>.value(
              _i8.dummyValue<_i5.ApiResponse<_i6.SessionDto>>(
                this,
                Invocation.method(#login, [userCredentials]),
              ),
            ),
          )
          as _i4.Future<_i5.ApiResponse<_i6.SessionDto>>);

  @override
  _i4.Future<_i5.ApiResponse<_i6.SessionDto>> register(
    Map<String, dynamic>? user,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [user]),
            returnValue: _i4.Future<_i5.ApiResponse<_i6.SessionDto>>.value(
              _i8.dummyValue<_i5.ApiResponse<_i6.SessionDto>>(
                this,
                Invocation.method(#register, [user]),
              ),
            ),
          )
          as _i4.Future<_i5.ApiResponse<_i6.SessionDto>>);
}

/// A class which mocks [AuthRepositoryRemoteInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepositoryRemoteInterface extends _i1.Mock
    implements _i9.AuthRepositoryRemoteInterface {
  MockAuthRepositoryRemoteInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Session> login(_i10.UserCredentials? userCredentials) =>
      (super.noSuchMethod(
            Invocation.method(#login, [userCredentials]),
            returnValue: _i4.Future<_i2.Session>.value(
              _FakeSession_0(
                this,
                Invocation.method(#login, [userCredentials]),
              ),
            ),
          )
          as _i4.Future<_i2.Session>);

  @override
  _i4.Future<_i2.Session> register(Map<String, dynamic>? user) =>
      (super.noSuchMethod(
            Invocation.method(#register, [user]),
            returnValue: _i4.Future<_i2.Session>.value(
              _FakeSession_0(this, Invocation.method(#register, [user])),
            ),
          )
          as _i4.Future<_i2.Session>);
}
